Parameters:
  StackName:
    Type: String

  TagKey:
    Type: String
  TagValue:
    Type: String

  ApiGatewayRoleArn:
    Type: String

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      AccountRecoverySetting: 
        RecoveryMechanisms: 
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig: 
        AllowAdminCreateUserOnly: false
      MfaConfiguration: 'OFF'
      DeviceConfiguration: 
        ChallengeRequiredOnNewDevice: false
        DeviceOnlyRememberedOnUserPrompt: false
      Policies:
        PasswordPolicy: 
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
          TemporaryPasswordValidityDays: 7
      UsernameAttributes: 
        - email
      UsernameConfiguration: 
        CaseSensitive: false
      UserPoolName: !Ref StackName

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties: 
      BinaryMediaTypes: 
        - image/png
        - application/octet-stream
      Description: !Sub '${StackName} API Gateway'
      Name: !Ref StackName
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  AgwAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    DependsOn:
      - RestApi
      - CognitoUserPool
    Properties: 
      AuthorizerCredentials: !Ref ApiGatewayRoleArn
      IdentitySource: COGNITO_USER_POOLS
      Name: !Ref StackName
      ProviderARNs: 
        - !Ref CognitoUserPool
      RestApiId: !Ref RestApi
      Type: COGNITO_USER_POOLS

  # API Gateway Resource
  AgwBookResource:
    Type: AWS::ApiGateway::Resource
    DependsOn: RestApi
    Properties: 
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: books
      RestApiId: !Ref RestApi

  AgwImageResource:
    Type: AWS::ApiGateway::Resource
    DependsOn: RestApi
    Properties: 
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: images
      RestApiId: !Ref RestApi

  # API Gateway Method
  # AgwMethodInsertBook:
  #   Type: AWS::ApiGateway::Method
  #   DependsOn:
  #     - AgwAuthorizer
  #   Properties: 
  #     AuthorizationType: COGNITO_USER_POOLS
  #     AuthorizerId: !Ref AgwAuthorizer
  #     HttpMethod: String
  #     Integration: 
  #       ConnectionType: INTERNET
  #       ContentHandling: CONVERT_TO_TEXT
  #       IntegrationHttpMethod: POST
  #       TimeoutInMillis: 29000
  #       Type: AWS_PROXY
  #       Uri: String
  #     OperationName: InsertBook
  #     ResourceId: !Ref AgwBookResource
  #     RestApiId: !Ref RestApi