
Parameters:
  TagKey:
    Type: String
    Default: Project
  TagValue:
    Type: String
    Default: aws-serverless-lab

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://aws-lab-cloudformation.s3-us-west-2.amazonaws.com/vpc.yml
      Parameters:
        StackName: !Ref AWS::StackName
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TimeoutInMinutes: 300

  IamStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VpcStack
    Properties:
      TemplateURL: https://aws-lab-cloudformation.s3-us-west-2.amazonaws.com/iam.yml
      Parameters:
        StackName: !Ref AWS::StackName
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TimeoutInMinutes: 300

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
      - IamStack
    Properties:
      TemplateURL: https://aws-lab-cloudformation.s3-us-west-2.amazonaws.com/lambda.yml
      Parameters:
        StackName: !Ref AWS::StackName
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
        SecurityGroupId: !GetAtt VpcStack.Outputs.LambdaSecurityGroup
        SubnetId1: !GetAtt VpcStack.Outputs.PrivateSubnet1
        SubnetId2: !GetAtt VpcStack.Outputs.PrivateSubnet2
        RoleArn: !GetAtt IamStack.Outputs.LambdaRoleArn
      TimeoutInMinutes: 300

  # DatastoreServicesStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn: 
  #     - VpcStack
  #   Properties:
  #     TemplateURL: https://aws-lab-cloudformation.s3-us-west-2.amazonaws.com/datastore-services.yml
  #     Parameters:
  #       StackName: !Ref AWS::StackName
  #       TagKey: !Ref TagKey
  #       TagValue: !Ref TagValue
  #       Vpc: !GetAtt VpcStack.Outputs.Vpc
  #       EsSubnet: !GetAtt VpcStack.Outputs.PrivateSubnet1
  #       ElasticsearchSecurityGroup: !GetAtt VpcStack.Outputs.ElasticsearchSecurityGroup
  #     TimeoutInMinutes: 300

  ApiGatewayServicesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - IamStack
      - VpcStack
    Properties:
      TemplateURL: https://aws-lab-cloudformation.s3-us-west-2.amazonaws.com/api-gateway-services.yml
      Parameters:
        StackName: !Ref AWS::StackName
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
        ApiGatewayRoleArn: !GetAtt IamStack.Outputs.ApiGatewayRoleArn
      TimeoutInMinutes: 300
