Parameters:
  StackName:
    Type: String

  TagKey:
    Type: String
  TagValue:
    Type: String

Resources:

  # Lambda Execution Role
  LambdaPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - LambdaRole
    Properties: 
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
      PolicyName: !Sub ${StackName}-LambdaPolicy
      Roles:
        - !Ref LambdaRole

  LambdaRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Description: Role for Lambda
      MaxSessionDuration: 3600
      RoleName: !Sub ${StackName}-LambdaRole
      Path: /
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue

  # API Gateway Role
  ApiGatewayPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - ApiGatewayRole
    Properties: 
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
      PolicyName: !Sub ${StackName}-ApiGatewayPolicy
      Roles:
        - !Ref ApiGatewayRole

  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "apigateway.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Description: Role for API Gateway
      MaxSessionDuration: 3600
      RoleName: !Sub ${StackName}-ApiGatewayRole
      Path: /
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue

Outputs:
  ApiGatewayRole:
    Description: ApiGatewayRole Name
    Value: !Ref ApiGatewayRole
    Export:
      Name: !Sub ${StackName}-ApiGatewayRole

  ApiGatewayRoleArn:
    Description: ApiGatewayRole ARN
    Value: !GetAtt ApiGatewayRole.Arn
    Export:
      Name: !Sub ${StackName}-ApiGatewayRoleArn

  LambdaRole:
    Description: LambdaRole Name
    Value: !Ref LambdaRole
    Export:
      Name: !Sub ${StackName}-LambdaRole

  LambdaRoleArn:
    Description: LambdaRole ARN
    Value: !GetAtt LambdaRole.Arn
    Export:
      Name: !Sub ${StackName}-LambdaRoleArn