
Parameters:
  StackName:
    Type: String

  TagKey:
    Type: String
  TagValue:
    Type: String

  Vpc:
    Type: String
  Subnet1:
    Type: String
  Subnet2:
    Type: String

Resources:

  Nlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      LoadBalancerAttributes: 
        - Key: load_balancing.cross_zone.enabled
          Value: true
      Name: !Ref StackName
      Scheme: internal
      Subnets: 
        - !Ref Subnet1
        - !Ref Subnet2
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue
      Type: network

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Name: !Ref StackName
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue
      TargetGroupAttributes: 
        - Key: deregistration_delay.connection_termination.enabled
          Value: true
      TargetType: lambda
      VpcId: !Ref Vpc

  # Listener
  # https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - Nlb
      - TargetGroup
    Properties: 
      DefaultActions: 
        - ForwardConfig: 
            ForwardConfig
          TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref Nlb
      Port: 80
      Protocol: String
      SslPolicy: String
Outputs:
  Nlb:
    Description: Information about the value
    Value: !Ref Nlb
    Export:
      Name: !Sub ${StackName}-nlb