Parameters:
  StackName:
    Type: String

  TagKey:
    Type: String
  TagValue:
    Type: String

  EsDomain:
    Type: String
    Default: es.fptu.net
  DomainAcmArn:
    Type: String
    Default: arn:aws:acm:us-west-2:900171207117:certificate/60fa02b4-870c-44be-85ca-3eb6aaf32f4e

  Vpc:
    Type: String
  EsSubnet:
    Type: String

  ElasticsearchSecurityGroup:
    Type: String

Resources:
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions:
        - AttributeName: owner_id
          AttributeType: 'S'
        - AttributeName: owner_name
          AttributeType: 'S'
        - AttributeName: name
          AttributeType: 'S'
        - AttributeName: price
          AttributeType: 'N'
      BillingMode: PROVISIONED
      KeySchema: 
        - AttributeName: name
          KeyType: HASH # partition key
        - AttributeName: owner_id
          KeyType: RANGE # sort key
      LocalSecondaryIndexes: 
        - IndexName: OwnerNameIndex
          KeySchema: 
            - AttributeName: name
              KeyType: HASH # partition key
            - AttributeName: owner_name
              KeyType: RANGE # sort key
          Projection: 
            ProjectionType: ALL
      PointInTimeRecoverySpecification: 
        PointInTimeRecoveryEnabled: true
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification: 
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Ref StackName
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue

  InventoryBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub ${StackName}-inventory-bucket
      LifecycleConfiguration: 
        Rules: 
          - Id: TransitionOfObject
            Status: Enabled
            Transitions: 
              - StorageClass: INTELLIGENT_TIERING
                TransitionInDays: 7
              - StorageClass: GLACIER
                TransitionInDays: 90
              - StorageClass: DEEP_ARCHIVE
                TransitionInDays: 180
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue

  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub ${StackName}-logging-bucket
      AccessControl: LogDeliveryWrite
      LifecycleConfiguration: 
        Rules: 
          - Id: TransitionOfObject
            Status: Enabled
            Transitions: 
              - StorageClass: INTELLIGENT_TIERING
                TransitionInDays: 7
              - StorageClass: GLACIER
                TransitionInDays: 90
              - StorageClass: DEEP_ARCHIVE
                TransitionInDays: 180
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue

  MasterBucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - InventoryBucket
      - LoggingBucket
    Properties: 
      BucketName: !Sub ${StackName}-master-bucket
      IntelligentTieringConfigurations: 
        - Id: ArchiveToGlacierAfter90Days
          Status: Enabled
          Tierings: 
            - AccessTier: ARCHIVE_ACCESS
              Days: 180
        - Id: ArchiveToDeepGlacierAfter180Days
          Status: Enabled
          Tierings: 
            - AccessTier: DEEP_ARCHIVE_ACCESS
              Days: 365
      InventoryConfigurations: 
        - Destination: 
            BucketAccountId: !Ref AWS::AccountId
            BucketArn: !GetAtt InventoryBucket.Arn
            Format: CSV
            Prefix: !Sub ${StackName}-master-bucket
          Enabled: true
          Id: MasterBucketInventoryConfig
          IncludedObjectVersions: All
          ScheduleFrequency: Daily
      LifecycleConfiguration: 
        Rules: 
          - AbortIncompleteMultipartUpload: 
              DaysAfterInitiation: 7
            ExpirationInDays: 7
            Id: DeleteExpiredMultipartUpload
            Status: Enabled
          - Id: RetentionOfOldVersion
            NoncurrentVersionExpirationInDays: 700 # keep older version up to 2 years
            Status: Enabled
          - Id: TransitionOfOldVersion
            NoncurrentVersionTransitions: 
              - StorageClass: INTELLIGENT_TIERING
                TransitionInDays: 7
              - StorageClass: GLACIER
                TransitionInDays: 90
              - StorageClass: DEEP_ARCHIVE
                TransitionInDays: 180
            Status: Enabled
          - ExpirationInDays: 3650 # keep objects for maximum up to 10 years
            Id: RetentionOfObject
            Status: Enabled
          - Id: TransitionOfObject
            Status: Enabled
            Transitions: 
              - StorageClass: INTELLIGENT_TIERING
                TransitionInDays: 30
              - StorageClass: GLACIER
                TransitionInDays: 180
              - StorageClass: DEEP_ARCHIVE
                TransitionInDays: 365
      LoggingConfiguration: 
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: !Sub ${StackName}-master-bucket
      OwnershipControls: 
        Rules: 
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue
      VersioningConfiguration: 
        Status: Enabled

  Elasticsearch:
    Type: AWS::Elasticsearch::Domain
    Properties: 
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*
      DomainEndpointOptions: 
        CustomEndpoint: !Ref EsDomain
        CustomEndpointCertificateArn: !Ref DomainAcmArn
        CustomEndpointEnabled: true
        EnforceHTTPS: true
        TLSSecurityPolicy: 'Policy-Min-TLS-1-2-2019-07'
      DomainName: !Ref StackName
      EBSOptions: 
        EBSEnabled: true
        VolumeSize: 20
        VolumeType: gp2
      ElasticsearchVersion: 7.9
      SnapshotOptions: 
        AutomatedSnapshotStartHour: 2
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue
      VPCOptions:
        SubnetIds:
          - !Ref EsSubnet
        SecurityGroupIds:
          - !Ref ElasticsearchSecurityGroup
      ElasticsearchClusterConfig:
        InstanceCount: 1
        InstanceType: t3.medium.elasticsearch
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'

Outputs:
  ElasticsearchResourceName:
    Description: Elasticsearch resource name
    Value: !Ref Elasticsearch
    Export:
      Name: !Sub ${StackName}-ElasticsearchResourceName
  ElasticsearchArn:
    Description: Elasticsearch Arn
    Value: !GetAtt Elasticsearch.Arn
    Export:
      Name: !Sub ${StackName}-ElasticsearchArn
  ElasticsearchDomainArn:
    Description: Elasticsearch DomainArn
    Value: !GetAtt Elasticsearch.DomainArn
    Export:
      Name: !Sub ${StackName}-ElasticsearchDomainArn
  ElasticsearchDomainEndpoint:
    Description: Elasticsearch DomainEndpoint
    Value: !GetAtt Elasticsearch.DomainEndpoint
    Export:
      Name: !Sub ${StackName}-ElasticsearchDomainEndpoint

