AWSTemplateFormatVersion: 2010-09-09
Description: >-
  aws-labs

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 100
    Handler: src/handlers/book-management.index
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref SampleTable
    Environment:
      Variables:
        TABLE_NAME: !Ref SampleTable

Resources:

  indexFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.index
      Description: Function to list books
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

  showFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.show
      Description: Function to show a book
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
 
  createFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.create
      Description: Function to create a book
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  updateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.update
      Description: Function to update a book
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  removeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.remove
      Description: Function to delete a book
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST