AWSTemplateFormatVersion: 2010-09-09
Description: >-
  aws-labs

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  TableName: taquy

Globals:
  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 100
    Handler: src/handlers/book-management.index
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TableName
    Environment:
      Variables:
        TABLE_NAME: !Ref TableName

Resources:
  indexFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.index
      Description: Function to list books

  showFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.show
      Description: Function to show a book

  createFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.create
      Description: Function to create a book

  updateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.update
      Description: Function to update a book

  removeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.remove
      Description: Function to delete a book
