AWSTemplateFormatVersion: 2010-09-09
Description: >-
  aws-labs

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 100
    Handler: index.handler
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref SampleTable
    Environment:
      Variables:
        TABLE_NAME: !Ref SampleTable

Resources:

  indexFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.getAllItemsHandler
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

  showFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.getByIdHandler
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
 
  createFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.putItemHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  updateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.putItemHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  removeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book-management.putItemHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST